
HP_PERCENT = 50
MP_PERCENT = 50
HP_KEY = 'del'
MP_KEY = 'end'
JUMP_KEY ='alt'
ATTACK_KEY ='shift'
TELEPORT_KEY = 'c'
TELEPORT_COOLDOWN_SEC = 1.5
OTHER_APPEAR_ACTION_DELAY_SEC = 7.0

RANGE_FRONT = 220
RANGE_BACK =0
RANGE_UP = 30
RANGE_DOWN = 30

IN_PLACE_DELAY = 0.5


REACH_LADDER_MOVING = 5