
HP_PERCENT = 50
MP_PERCENT = 50
HP_KEY = 'del'
MP_KEY = 'end'
JUMP_KEY ='alt'
ATTACK_KEY ='shift'
TELEPORT_KEY = 'c'
TELEPORT_COOLDOWN_SEC = 1.5
OTHER_APPEAR_ACTION_DELAY_SEC = 7.0

RANGE_FRONT = 220
RANGE_BACK =0
RANGE_UP = 30
RANGE_DOWN = 30

IN_PLACE_DELAY = 0.5
ROUTINE_RANDOM_INTERVAL_SEC = 60 * 3

# Channel switch scheduler (test: 1 minute)
CHANNEL_SWITCH_INTERVAL_SEC = 60 * 60 * 60
CHANNEL_SWITCH_RETRY_SEC = 60
CHANNEL_SWITCH_MATCH_THRESHOLD = 0.75
CHANNEL_SWITCH_LOAD_TIMEOUT_SEC = 45

# Safe ladder waypoint before channel switch
CHANNEL_SWITCH_SAFE_LADDER_X = 35
CHANNEL_SWITCH_SAFE_LADDER_Y = 119
CHANNEL_SWITCH_SAFE_LADDER_END_Y = 127 # 84
CHANNEL_SWITCH_SAFE_LADDER_TIMEOUT_SEC = 25

# Channel switch position gate (-1 disables that axis check)
CHANNEL_SWITCH_POS_X = -1
CHANNEL_SWITCH_POS_Y = -1
CHANNEL_SWITCH_POS_TOL_X = 8
CHANNEL_SWITCH_POS_TOL_Y = 8

# Re-check delay when position gate is not satisfied
CHANNEL_SWITCH_WAIT_CHECK_SEC = 2.0


REACH_LADDER_MOVING = 5
